spring:
  application:
    name: workflow-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/workflow_platform
      auto-index-creation: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.workflow: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

restheart:
  base-url: http://localhost:8080/
  username: admin
  password: secret

secret:
  key: e7440e98a7c9dfc3ee87f7238064c883e04f800f3674dea3e26ceffbb41d7d13

